# Generated by Django 3.0.8 on 2020-08-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpo',
            old_name='amp_name',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='cmpo',
            table='main_cmpo',
        ),
    ]
