# Generated by Django 3.0.8 on 2020-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_index',
            name='a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='active',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='cri_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='e',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='ex',
            field=models.CharField(choices=[('pp', 'PP&P Excellence'), ('se', 'Service'), ('pe', 'People Excellence'), ('ge', 'Government Excellence')], default='pp', max_length=15),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='f',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='goal',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='h_kpi',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='hdc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='kpi_formular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='kpi_formular_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='kpi_year',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='main_kpi_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='pa',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='respon',
            field=models.CharField(choices=[('1', 'พัฒนายุทธศาสตร์สาธารณสุข'), ('2', 'บริหารทั่วไป'), ('3', 'ทันตสาธารณสุข'), ('4', 'ควบคุมโรคติดต่อ'), ('5', 'คุ้มครองผู้บริโภคและเภสัชสาธารณสุข'), ('6', 'บริหารทรัพยากรบุคคล'), ('7', 'นิติกร'), ('8', 'พัฒนาคุณภาพและสรุปแบบบริการ'), ('9', 'ส่งเสริมสุขภาพ'), ('10', 'อนามัยสิ่งแวดล้อมและอาชีวอนามัย'), ('11', 'ประกันสุขภาพ'), ('12', 'ควบคุมโรคไม่ติดต่อ สุขภาพจิตและยาเสพติด'), ('13', 'แพทย์แผนไทยและการแพทย์ทางเลือก'), ('14', 'สุขศึกษาประชาสัมพันธ์')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='static_target',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='success_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='unit',
            field=models.CharField(choices=[('1', '-'), ('2', 'ร้อยละ'), ('3', 'ต่อแสนประชากร')], default='1', max_length=100),
        ),
    ]
