# Generated by Django 3.0.8 on 2020-07-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200730_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_index',
            name='unit',
            field=models.CharField(choices=[('1', '-'), ('2', 'ร้อยละ'), ('3', 'ต่อแสนประชากร'), ('4', 'คน')], default='1', max_length=100),
        ),
    ]
