# Generated by Django 3.0.8 on 2020-08-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200731_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_index',
            name='ex',
            field=models.CharField(choices=[('pp', 'PP&P Excellence'), ('se', 'Service'), ('pe', 'People Excellence'), ('ge', 'Government Excellence'), ('ncd', 'NCD')], default='pp', max_length=15),
        ),
        migrations.AlterField(
            model_name='kpi_index',
            name='unit',
            field=models.CharField(choices=[('1', '-'), ('2', 'ร้อยละ'), ('3', 'ต่อแสนประชากร'), ('4', 'คน'), ('5', 'แห่ง'), ('6', '%'), ('7', 'เรื่อง'), ('8', 'เขตสุขภาพ'), ('9', 'ฉบับ'), ('10', 'ครอบครัว'), ('11', 'ต่อร้อยประชากร')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='response',
            field=models.CharField(choices=[('1', 'พัฒนายุทธศาสตร์สาธารณสุข'), ('2', 'บริหารทั่วไป'), ('3', 'ทันตสาธารณสุข'), ('4', 'ควบคุมโรคติดต่อ'), ('5', 'คุ้มครองผู้บริโภคและเภสัชสาธารณสุข'), ('6', 'บริหารทรัพยากรบุคคล'), ('7', 'นิติกร'), ('8', 'พัฒนาคุณภาพและสรุปแบบบริการ'), ('9', 'ส่งเสริมสุขภาพ'), ('10', 'อนามัยสิ่งแวดล้อมและอาชีวอนามัย'), ('11', 'ประกันสุขภาพ'), ('12', 'ควบคุมโรคไม่ติดต่อ สุขภาพจิตและยาเสพติด'), ('13', 'แพทย์แผนไทยและการแพทย์ทางเลือก'), ('14', 'สุขศึกษาประชาสัมพันธ์'), ('15', 'None')], default='1', max_length=100),
        ),
    ]
